config/routes.rb
Rails.application.routes.draw do
  resources :detalle_pedidos
  resources :pedidos do
    member do
      get :atender
    end
  end
  resources :menus
  resources :clientes
  resources :mesas
  resources :restaurantes
  root to: 'restaurantes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :menus, only: :index
      resources :clientes, only: :index
      resources :pedidos, only: [:index, :create, :update]
      match '/pedidos' => "pedidos#create", via: :options
    end
  end
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  belongs_to :restaurante

  def restaurante_nombre
    restaurante.nombre
  end
end

app/controllers/api/v1/clientes_controller.rb
module Api
  module V1
    class ClientesController < ApplicationController
      respond_to :json

      def index
        respond_with Cliente.all
      end
    end
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nit, :nombre, :restaurante_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.haml
= form_with(model: cliente, local: true) do |form|
  - if cliente.errors.any?
    #error_explanation
      %h2
        = pluralize(cliente.errors.count, "error")
        prohibited this cliente from being saved:
      %ul
        - cliente.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :nit
    = form.text_field :nit, id: :cliente_nit
  .field
    = form.label :nombre
    = form.text_field :nombre, id: :cliente_nombre
  .field
    = form.label :restaurante_id
    = form.select :restaurante_id, options_from_collection_for_select(Restaurante.all, 'id', 'nombre')
  .actions
    = form.submit

app/views/clientes/edit.html.haml
%h1 Editing Cliente
= render 'form', cliente: @cliente
= link_to 'Show', @cliente
|
= link_to 'Back', clientes_path

app/views/clientes/index.html.haml
%p#notice= notice
.container-fluid
  .row
    %main.col-sm-9.ml-sm-auto.col-md-12.pt-3{:role => "main"}
      %h1 Clientes
      .table-responsive
        %table.table.table-striped
          %thead
            %tr
              %th NIT
              %th Nombre
              %th Restaurante
              %th Acciones
          %tbody
            - @clientes.each do |cliente|
              %tr
                %td= cliente.nit
                %td= cliente.nombre
                %td= link_to cliente.restaurante_nombre, restaurante_path(cliente.restaurante.id)
                %td
                  = link_to 'Mostrar', cliente, class: 'btn btn-primary btn-sm'
                  = link_to 'Editar', edit_cliente_path(cliente), class: 'btn btn-info btn-sm'
                  = link_to 'Eliminar', cliente, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: '¿Estas seguro?' }
%br
= link_to 'Nuevo Cliente', new_cliente_path, class: 'btn btn-primary'

app/views/clientes/new.html.haml
%h1 New Cliente
= render 'form', cliente: @cliente
= link_to 'Back', clientes_path

app/views/clientes/show.html.haml
%h2 Cliente

%p#notice= notice
%p
  %strong Nit:
  = @cliente.nit
%p
  %strong Nombre:
  = @cliente.nombre
%p
  %strong Restaurante:
  = link_to @cliente.restaurante_nombre, restaurante_path(@cliente.restaurante.id)

= link_to 'Editar', edit_cliente_path(@cliente)
|
= link_to 'Atrás', clientes_path