config/routes.rb
Rails.application.routes.draw do
  resources :detalle_pedidos
  resources :pedidos do
    member do
      get :atender
    end
  end
  resources :menus
  resources :clientes
  resources :mesas
  resources :restaurantes
  root to: 'restaurantes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :menus, only: :index
      resources :clientes, only: :index
      resources :pedidos, only: [:index, :create, :update]
      match '/pedidos' => "pedidos#create", via: :options
    end
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurante

  def restaurante_nombre
    restaurante.nombre
  end
end

app/controllers/api/v1/menus_controller.rb
module Api
  module V1
    class MenusController < ApplicationController
      respond_to :json

      def index
        respond_with Menu.all
      end
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:codigo, :nombre, :precio, :restaurante_id)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.haml
= form_with(model: menu, local: true) do |form|
  - if menu.errors.any?
    #error_explanation
      %h2
        = pluralize(menu.errors.count, "error")
        prohibited this menu from being saved:
      %ul
        - menu.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :codigo
    = form.text_field :codigo, id: :menu_codigo
  .field
    = form.label :nombre
    = form.text_field :nombre, id: :menu_nombre
  .field
    = form.label :precio
    = form.text_field :precio, id: :menu_precio
  .field
    = form.label :restaurante_id
    = form.select :restaurante_id, options_from_collection_for_select(Restaurante.all, 'id', 'nombre')
  .actions
    = form.submit

app/views/menus/edit.html.haml
%h1 Editing Menu
= render 'form', menu: @menu
= link_to 'Show', @menu
|
= link_to 'Back', menus_path

app/views/menus/index.html.haml
%p#notice= notice
.container-fluid
  .row
    %main.col-sm-9.ml-sm-auto.col-md-12.pt-3{:role => "main"}
      %h1 Menús
      .table-responsive
        %table.table.table-striped
          %thead
            %tr
              %th Código
              %th Nombre
              %th Precio
              %th Restaurante
              %th Acciones
          %tbody
            - @menus.each do |menu|
              %tr
                %td= menu.codigo
                %td= menu.nombre
                %td= formato_bs(menu.precio)
                %td= menu.restaurante_nombre
                %td
                  = link_to 'Mostrar', menu, class: 'btn btn-primary btn-sm'
                  = link_to 'Editar', edit_menu_path(menu), class: 'btn btn-info btn-sm'
                  = link_to 'Eliminar', menu, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: '¿Estas seguro?' }

%br/
= link_to 'Adicionar menú', new_menu_path, class: 'btn btn-primary'

app/views/menus/new.html.haml
%h1 New Menu
= render 'form', menu: @menu
= link_to 'Back', menus_path

app/views/menus/show.html.haml
%h2 Menú

%p#notice= notice
%p
  %strong Codigo:
  = @menu.codigo
%p
  %strong Nombre:
  = @menu.nombre
%p
  %strong Precio:
  = @menu.precio
%p
  %strong Restaurante:
  = link_to @menu.restaurante_nombre, restaurante_path(@menu.restaurante.id)

= link_to 'Editar', edit_menu_path(@menu)
|
= link_to 'Atrás', menus_path