config/routes.rb
Rails.application.routes.draw do
  resources :detalle_pedidos
  resources :pedidos do
    member do
      get :atender
    end
  end
  resources :menus
  resources :clientes
  resources :mesas
  resources :restaurantes
  root to: 'restaurantes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :menus, only: :index
      resources :clientes, only: :index
      resources :pedidos, only: [:index, :create, :update]
      match '/pedidos' => "pedidos#create", via: :options
    end
  end
end

app/models/mesa.rb
class Mesa < ApplicationRecord
  belongs_to :restaurante

  def restaurante_nombre
    restaurante.nombre
  end
end

app/controllers/mesas_controller.rb
class MesasController < ApplicationController
  before_action :set_mesa, only: [:show, :edit, :update, :destroy]

  # GET /mesas
  # GET /mesas.json
  def index
    @mesas = Mesa.all
  end

  # GET /mesas/1
  # GET /mesas/1.json
  def show
    require 'rqrcode'
    @qr = RQRCode::QRCode.new("#{@mesa.restaurante_nombre}|#{@mesa.restaurante_id}|#{@mesa.numero}|#{@mesa.id}", size: 4, level: :h)
  end

  # GET /mesas/new
  def new
    @mesa = Mesa.new
  end

  # GET /mesas/1/edit
  def edit
  end

  # POST /mesas
  # POST /mesas.json
  def create
    @mesa = Mesa.new(mesa_params)

    respond_to do |format|
      if @mesa.save
        format.html { redirect_to @mesa, notice: 'Mesa was successfully created.' }
        format.json { render :show, status: :created, location: @mesa }
      else
        format.html { render :new }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mesas/1
  # PATCH/PUT /mesas/1.json
  def update
    respond_to do |format|
      if @mesa.update(mesa_params)
        format.html { redirect_to @mesa, notice: 'Mesa was successfully updated.' }
        format.json { render :show, status: :ok, location: @mesa }
      else
        format.html { render :edit }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mesas/1
  # DELETE /mesas/1.json
  def destroy
    @mesa.destroy
    respond_to do |format|
      format.html { redirect_to mesas_url, notice: 'Mesa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mesa
      @mesa = Mesa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mesa_params
      params.require(:mesa).permit(:numero, :restaurante_id)
    end
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/views/mesas/_form.html.haml
= form_with(model: mesa, local: true) do |form|
  - if mesa.errors.any?
    #error_explanation
      %h2
        = pluralize(mesa.errors.count, "error")
        prohibited this mesa from being saved:
      %ul
        - mesa.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :numero
    = form.number_field :numero, id: :mesa_numero
  .field
    = form.label :restaurante_id
    = form.select :restaurante_id, options_from_collection_for_select(Restaurante.all, 'id', 'nombre')
  .actions
    = form.submit

app/views/mesas/edit.html.haml
%h1 Editing Mesa
= render 'form', mesa: @mesa
= link_to 'Show', @mesa
|
= link_to 'Back', mesas_path

app/views/mesas/index.html.haml
%p#notice= notice
.container-fluid
  .row
    %main.col-sm-9.ml-sm-auto.col-md-12.pt-3{:role => "main"}
      %h1 Mesas
      .table-responsive
        %table.table.table-striped
          %thead
            %tr
              %th Número
              %th Restaurante
              %th Acciones
          %tbody
            - @mesas.each do |mesa|
              %tr
                %td= mesa.numero
                %td= link_to mesa.restaurante_nombre, restaurante_path(mesa.restaurante.id)
                %td
                  = link_to 'Mostrar', mesa, class: 'btn btn-primary btn-sm'
                  = link_to 'Editar', edit_mesa_path(mesa), class: 'btn btn-info btn-sm'
                  = link_to 'Eliminar', mesa, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: '¿Estas seguro?' }
%br/
= link_to 'Nueva Mesa', new_mesa_path, class: 'btn btn-primary'

app/views/mesas/new.html.haml
%h1 New Mesa
= render 'form', mesa: @mesa
= link_to 'Back', mesas_path

app/views/mesas/show.html.haml
%h2 Mesa
%p#notice= notice
%p
  %strong Numero:
  = @mesa.numero
%p
  %strong Restaurante:
  = link_to @mesa.restaurante_nombre, restaurante_path(@mesa.restaurante.id)
%p
  %strong QR:
  .qr
    = raw @qr.as_html
= link_to 'Editar', edit_mesa_path(@mesa)
|
= link_to 'Atrás', mesas_path