config/routes.rb
Rails.application.routes.draw do
  resources :detalle_pedidos
  resources :pedidos do
    member do
      get :atender
    end
  end
  resources :menus
  resources :clientes
  resources :mesas
  resources :restaurantes
  root to: 'restaurantes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :menus, only: :index
      resources :clientes, only: :index
      resources :pedidos, only: [:index, :create, :update]
      match '/pedidos' => "pedidos#create", via: :options
    end
  end
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :mesa
  belongs_to :cliente, optional: true

  has_many :detalle_pedidos

  scope :recientes, -> { order('numero DESC') }
  scope :estados, -> { order('estado DESC') }
  scope :solicitados, -> { where(estado: 'SOLICITADO') }
  scope :atendidos, -> { where(estado: 'ATENDIDO') }

  before_create :asignar_numero

  def atender
    update_attributes(estado: 'ATENDIDO')
  end

  def atendido?
    estado == 'ATENDIDO'
  end

  def solicitado?
    estado == 'SOLICITADO'
  end

  def mesa_numero
    mesa.numero
  end

  def cliente_nombre
    cliente.present? ? cliente.nombre : 'NN'
  end

  def calcular_total
    total = 0
    detalle_pedidos.each do |detalle_pedido|
      total += detalle_pedido.menu.precio * detalle_pedido.cantidad
    end
    update_attributes(total: total)
  end

  private

  def asignar_numero
    maximo = Pedido.maximum :numero
    self.numero = maximo.present? ? maximo + 1 : 1
  end
end

app/controllers/api/v1/pedidos_controller.rb
module Api
  module V1
    class PedidosController < ApplicationController
      include ActionController::RequestForgeryProtection
      protect_from_forgery with: :exception, unless: -> { request.format.json? }
      respond_to :json

      def index
        respond_with Pedido.all.order('estado DESC, numero DESC')
      end

      def create
        puts params
        @pedido = Pedido.new(eval(params[:pedido]))
        if @pedido.save
          DetallePedido.crear_detalles(@pedido.id, eval('[' + params[:detalle_pedido][0] + ']'))
          render json: @pedido
        else
          render json: @pedido.errors
        end
      end

      def update
        respond_with Cliente.all
      end

      private

      def pedido_params
        params.require(:pedido)
      end

      def detalle_pedido_params
        params.require(:detalle_pedido)
      end
    end
  end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all.order('estado DESC, numero DESC')
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def atender
    @pedido = Pedido.find (params[:id])
    @pedido.atender
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido fue atendido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:numero, :total, :mesa_id, :cliente)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.haml
= form_with(model: pedido, local: true) do |form|
  - if pedido.errors.any?
    #error_explanation
      %h2
        = pluralize(pedido.errors.count, "error")
        prohibited this pedido from being saved:
      %ul
        - pedido.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :numero
    = form.number_field :numero, id: :pedido_numero
  .field
    = form.label :total
    = form.text_field :total, id: :pedido_total
  .field
    = form.label :mesa_id
    = form.select :mesa_id, options_from_collection_for_select(Mesa.all, 'id', 'numero')
  .field
    = form.label :cliente
    = form.select :cliente_id, options_from_collection_for_select(Cliente.all, 'id', 'nombre')
  .actions
    = form.submit

app/views/pedidos/edit.html.haml
%h1 Editing Pedido
= render 'form', pedido: @pedido
= link_to 'Show', @pedido
|
= link_to 'Back', pedidos_path

app/views/pedidos/index.html.haml
.container-fluid
  .row
    %main.col-sm-9.ml-sm-auto.col-md-12.pt-3{:role => "main"}
      %h1 Pedidos
      .table-responsive
        %table.table.table-striped
          %thead
            %tr
              %th #
              %th Mesa
              %th Cliente
              %th Precio
              %th Estado
              %th Acciones
          %tbody
            - @pedidos.each do |pedido|
              %tr
                %td= pedido.numero
                %td= pedido.mesa_numero
                %td= pedido.cliente_nombre
                %td= formato_bs(pedido.total)
                %td
                  - if pedido.atendido?
                    %button.btn.btn-success.btn-sm{:type => "button"} #{ pedido.estado }
                  - else
                    %button.btn.btn-danger.btn-sm{:type => "button"} #{pedido.estado}
                %td
                  = link_to 'Mostrar', pedido, class: 'btn btn-primary btn-sm'
                  - if pedido.solicitado?
                    = link_to 'Atender', atender_pedido_path(pedido), class: 'btn btn-info btn-sm'

%br/
= link_to 'Nuevo Pedido', new_pedido_path, class: 'btn btn-primary'

app/views/pedidos/new.html.haml
%h1 New Pedido
= render 'form', pedido: @pedido
= link_to 'Back', pedidos_path

app/views/pedidos/show.html.haml
%h1 Pedido ##{@pedido.numero}
%p#notice= notice
%p
  %strong Restaurante:
  = link_to @pedido.mesa.restaurante_nombre, restaurante_path(@pedido.mesa.restaurante_id)
%p
  %strong Mesa:
  = link_to @pedido.mesa_numero, mesa_path(@pedido.mesa.id)
%p
  %strong Cliente:
  - if @pedido.cliente.present?
    = link_to @pedido.cliente_nombre, cliente_path(@pedido.cliente.id)
  - else
    NN
%p
  %strong Total:
  %strong
    = formato_bs(@pedido.total)
.container-fluid
  .row
    %main.col-sm-9.ml-sm-auto.col-md-12.pt-3{:role => "main"}
      %h1 Detalle Pedido
      .table-responsive
        %table.table.table-striped
          %thead
            %tr
              %th Código Menú
              %th Nombre
              %th Precio
              %th Cantidad
              %th Sub-total
          %tbody
            - total = 0
            - @pedido.detalle_pedidos.each do |detalle_pedido|
              %tr
                %td= detalle_pedido.menu.codigo
                %td= detalle_pedido.menu.nombre
                %td= formato_bs(detalle_pedido.menu.precio)
                %td= detalle_pedido.cantidad
                - subtotal = detalle_pedido.menu.precio * detalle_pedido.cantidad
                - total += subtotal
                %td= formato_bs(subtotal)
            %tr
              %td{colspan: 4}
                %strong Total
              %td
                %strong= formato_bs(total)
= link_to 'Atrás', pedidos_path

#timeline
  / load more button
  %button {{message}}
  / tweet object
  {{#tweets}}
  {{> tweet}}
  {{/tweets}}